services:
  qdrant-mcp:
    image: qdrant-mcp-server:v3.3.5

    build:
      context: .
      dockerfile: Dockerfile
      args:
        QDRANT_MCP_BRANCH: ${QDRANT_MCP_BRANCH}

    env_file:
      - .env

    container_name: qdrant-mcp

    restart: unless-stopped

    user: "${CONTAINER_UID}:${CONTAINER_GID}"

    volumes:
      - /volume1/docker/shared_data/qdrant-mcp:/sources:rw

    ports:
      - "3001:3000"

    networks:
      - rag

networks:
  rag:
    external: true
    name: rag
